# Generated by Django 4.2.4 on 2023-08-22 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembertranslation',
            name='about',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammembertranslation',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
