# Generated by Django 4.2.4 on 2023-08-22 07:22

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_alter_teammembertranslation_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='employe.teammember'),
        ),
    ]
